"""
train.py
========
Trains an XGBoost multi-class congestion classifier on the synthetic
network telemetry dataset generated by data/generate_data.py.

Usage:
    python train.py                   # auto-generates data if CSV missing
    python train.py --data data/network_telemetry.csv

Output:
    models/congestion_model.joblib    Trained sklearn Pipeline (scaler + XGBoost)
    models/label_encoder.joblib       LabelEncoder for class names
"""

import argparse
import os
import sys
import subprocess
import numpy as np
import pandas as pd
import joblib
import matplotlib
matplotlib.use("Agg")          # non-interactive backend (safe on headless servers)
import matplotlib.pyplot as plt

from sklearn.model_selection    import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing      import StandardScaler, LabelEncoder
from sklearn.pipeline           import Pipeline
from sklearn.metrics            import (
    accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
)
from xgboost import XGBClassifier


# ──────────────────────────────────────────────────────────────────────────────
# Paths
# ──────────────────────────────────────────────────────────────────────────────
BASE_DIR   = os.path.dirname(__file__)
DATA_PATH  = os.path.join(BASE_DIR, "data", "network_telemetry.csv")
MODEL_DIR  = os.path.join(BASE_DIR, "models")
MODEL_PATH = os.path.join(MODEL_DIR, "congestion_model.joblib")
LE_PATH    = os.path.join(MODEL_DIR, "label_encoder.joblib")
CM_PATH    = os.path.join(MODEL_DIR, "confusion_matrix.png")

os.makedirs(MODEL_DIR, exist_ok=True)

# ──────────────────────────────────────────────────────────────────────────────
# Feature columns used during training (must match FastAPI inference)
# ──────────────────────────────────────────────────────────────────────────────
FEATURES = ["throughput_mbps", "capacity_mbps", "delay_ms", "utilization_ratio"]
TARGET   = "congestion_status"

# ──────────────────────────────────────────────────────────────────────────────
# Class order (used by LabelEncoder and XGBoost)
# ──────────────────────────────────────────────────────────────────────────────
CLASS_ORDER = ["Uncongested", "Balanced", "Moderately Congested", "Highly Congested"]


def generate_data_if_missing(data_path: str) -> None:
    """Auto-run the data generator if the CSV doesn't exist yet."""
    if not os.path.exists(data_path):
        print("⚠️  Training data not found. Running generate_data.py …")
        gen_script = os.path.join(BASE_DIR, "data", "generate_data.py")
        subprocess.run([sys.executable, gen_script], check=True)


def load_data(data_path: str) -> pd.DataFrame:
    df = pd.read_csv(data_path)
    # Compute utilization_ratio in case the CSV was generated without it
    if "utilization_ratio" not in df.columns:
        df["utilization_ratio"] = df["throughput_mbps"] / df["capacity_mbps"]
    return df


def build_pipeline(n_classes: int) -> Pipeline:
    """
    sklearn Pipeline:
        StandardScaler  →  XGBClassifier (multi:softprob)

    XGBoost hyperparameters are chosen to balance accuracy vs. overfitting
    on a ~10k-row dataset with 4 clean classes.
    """
    xgb = XGBClassifier(
        n_estimators=300,
        max_depth=6,
        learning_rate=0.1,
        subsample=0.8,
        colsample_bytree=0.8,
        use_label_encoder=False,
        eval_metric="mlogloss",
        objective="multi:softprob",
        num_class=n_classes,
        random_state=42,
        n_jobs=-1,
    )
    return Pipeline([
        ("scaler", StandardScaler()),
        ("clf",    xgb),
    ])


def plot_confusion_matrix(y_true, y_pred, class_names: list, save_path: str) -> None:
    cm = confusion_matrix(y_true, y_pred, labels=class_names)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
    fig, ax = plt.subplots(figsize=(8, 6))
    disp.plot(ax=ax, colorbar=True, cmap="Blues")
    ax.set_title("Confusion Matrix — NDT Congestion Classifier", fontsize=13, pad=12)
    plt.xticks(rotation=20, ha="right")
    plt.tight_layout()
    plt.savefig(save_path, dpi=150)
    plt.close()
    print(f"📊 Confusion matrix saved → {save_path}")


def main(data_path: str) -> None:
    # ── 1. Data ──────────────────────────────────────────────────────────────
    generate_data_if_missing(data_path)
    df = load_data(data_path)

    print(f"\n📂 Loaded {len(df):,} rows from {data_path}")
    print("Class distribution:\n", df[TARGET].value_counts(), "\n")

    # ── 2. Encode labels ──────────────────────────────────────────────────────
    le = LabelEncoder()
    le.fit(CLASS_ORDER)                          # fix the order for consistency
    y_encoded = le.transform(df[TARGET])

    X = df[FEATURES].values
    y = y_encoded

    # ── 3. Train / test split ─────────────────────────────────────────────────
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=42
    )
    print(f"Train: {len(X_train):,}  |  Test: {len(X_test):,}")

    # ── 4. Build & train pipeline ─────────────────────────────────────────────
    pipe = build_pipeline(n_classes=len(CLASS_ORDER))
    print("\n🚀 Training XGBoost pipeline …")
    pipe.fit(X_train, y_train)

    # ── 5. Evaluate ───────────────────────────────────────────────────────────
    y_pred     = pipe.predict(X_test)
    y_pred_lbl = le.inverse_transform(y_pred)
    y_test_lbl = le.inverse_transform(y_test)

    acc = accuracy_score(y_test, y_pred)
    print(f"\n✅ Test Accuracy : {acc:.4f}  ({acc*100:.2f} %)")
    print("\nClassification Report:")
    print(classification_report(y_test_lbl, y_pred_lbl, target_names=CLASS_ORDER))

    # 5-fold cross-validation on full dataset
    print("Running 5-fold cross-validation …")
    cv_scores = cross_val_score(pipe, X, y, cv=StratifiedKFold(5, shuffle=True, random_state=42), scoring="accuracy")
    print(f"CV Accuracy: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}\n")

    # ── 6. Confusion matrix ───────────────────────────────────────────────────
    plot_confusion_matrix(y_test_lbl, y_pred_lbl, CLASS_ORDER, CM_PATH)

    # ── 7. Save artifacts ─────────────────────────────────────────────────────
    joblib.dump(pipe, MODEL_PATH)
    joblib.dump(le,   LE_PATH)
    print(f"💾 Model saved   → {MODEL_PATH}")
    print(f"💾 Encoder saved → {LE_PATH}")

    # ── 8. Quick sanity check ─────────────────────────────────────────────────
    print("\n🔬 Sanity check (3 sample predictions):")
    samples = np.array([
        [900.0,  1000, 45.2, 0.90],   # should be Highly Congested
        [400.0,  1000, 10.1, 0.40],   # should be Balanced
        [50.0,   500,  4.5,  0.10],   # should be Uncongested
    ])
    preds = le.inverse_transform(pipe.predict(samples))
    probs = pipe.predict_proba(samples).max(axis=1)
    for feat, lbl, prob in zip(samples, preds, probs):
        tput, cap, dms, util = feat
        print(f"  tput={tput:.0f}/{cap:.0f} Mbps  delay={dms} ms  util={util:.0%}  → {lbl:<25} (p={prob:.3f})")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train NDT congestion classifier")
    parser.add_argument("--data", default=DATA_PATH, help="Path to training CSV")
    args = parser.parse_args()
    main(args.data)
