"""
main.py
=======
FastAPI microservice for the NDT ML Engine.

Endpoints
---------
  POST /predict-congestion   → Main inference endpoint (called by Node.js backend)
  GET  /health               → Liveness probe
  GET  /docs                 → Swagger UI (auto-generated by FastAPI)

Usage
-----
    uvicorn app.main:app --reload --port 8000

Environment Variables
---------------------
  ML_MODEL_PATH   Override default model path  (default: ../models/congestion_model.joblib)
  ML_ENCODER_PATH Override default encoder path (default: ../models/label_encoder.joblib)
"""

import os
import logging
from contextlib import asynccontextmanager
from typing     import Optional

import numpy  as np
import joblib
from fastapi            import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from app.schemas import (
    PredictRequest, PredictResponse,
    EdgePrediction, HealthResponse,
)

# ──────────────────────────────────────────────────────────────────────────────
# Logging
# ──────────────────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("ndt-ml-engine")

# ──────────────────────────────────────────────────────────────────────────────
# Resolve model paths (relative to the ml-engine/ root)
# ──────────────────────────────────────────────────────────────────────────────
_ROOT        = os.path.dirname(os.path.dirname(__file__))   # ml-engine/
_MODEL_PATH  = os.environ.get("ML_MODEL_PATH",   os.path.join(_ROOT, "models", "congestion_model.joblib"))
_ENCODER_PATH= os.environ.get("ML_ENCODER_PATH", os.path.join(_ROOT, "models", "label_encoder.joblib"))

# ──────────────────────────────────────────────────────────────────────────────
# Feature order must match the order used during training (train.py → FEATURES)
# ──────────────────────────────────────────────────────────────────────────────
FEATURES = ["throughput_mbps", "capacity_mbps", "delay_ms", "utilization_ratio"]

# ──────────────────────────────────────────────────────────────────────────────
# Application state (populated during lifespan startup)
# ──────────────────────────────────────────────────────────────────────────────
_state: dict = {
    "pipeline": None,
    "encoder":  None,
    "loaded":   False,
}


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Load the ML model once on startup; clean up on shutdown."""
    log.info("🚀 NDT ML Engine starting …")
    try:
        _state["pipeline"] = joblib.load(_MODEL_PATH)
        _state["encoder"]  = joblib.load(_ENCODER_PATH)
        _state["loaded"]   = True
        log.info(f"✅ Model loaded   → {_MODEL_PATH}")
        log.info(f"✅ Encoder loaded → {_ENCODER_PATH}")
    except FileNotFoundError as e:
        log.error(
            f"❌ Model file not found: {e}\n"
            "   Run `python train.py` from ml-engine/ to generate the model first."
        )
        # Don't crash — let the /health endpoint report the issue
    yield
    log.info("👋 NDT ML Engine shutting down …")


# ──────────────────────────────────────────────────────────────────────────────
# FastAPI app
# ──────────────────────────────────────────────────────────────────────────────
app = FastAPI(
    title="NDT ML Engine",
    description=(
        "Predictive Network Digital Twin — Congestion Classification Microservice.\n\n"
        "Classifies each network edge into one of four congestion levels "
        "(**Uncongested**, **Balanced**, **Moderately Congested**, **Highly Congested**) "
        "using a trained XGBoost model."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

# Allow requests from the Node.js backend (port 4000) and the frontend (port 3000)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:4000", "http://localhost:3000", "*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ──────────────────────────────────────────────────────────────────────────────
# Endpoints
# ──────────────────────────────────────────────────────────────────────────────

@app.get("/health", response_model=HealthResponse, tags=["Monitoring"])
async def health():
    """Liveness probe — also reports whether the model has been loaded."""
    return HealthResponse(
        status="ok",
        model_loaded=_state["loaded"],
        version="1.0.0",
    )


@app.post(
    "/predict-congestion",
    response_model=PredictResponse,
    tags=["Inference"],
    summary="Predict congestion status for a list of network edges",
)
async def predict_congestion(request: PredictRequest) -> PredictResponse:
    """
    Accepts a list of network edges with real-time telemetry and returns
    a congestion prediction + probability for each edge.

    This endpoint is called by `backend/services/mockML.js` (after the SDE
    team swaps the mock with the real axios call).
    """
    if not _state["loaded"]:
        raise HTTPException(
            status_code=503,
            detail=(
                "Model not loaded. "
                "Please run `python train.py` from ml-engine/ and restart the server."
            ),
        )

    pipeline = _state["pipeline"]
    encoder  = _state["encoder"]

    # ── Build feature matrix ─────────────────────────────────────────────────
    rows = []
    for edge in request.edges:
        util = edge.throughput_mbps / edge.capacity_mbps
        rows.append([
            edge.throughput_mbps,
            edge.capacity_mbps,
            edge.delay_ms,
            util,                   # derived feature: utilization_ratio
        ])

    X = np.array(rows, dtype=np.float64)

    # ── Inference ─────────────────────────────────────────────────────────────
    try:
        encoded_preds = pipeline.predict(X)
        probabilities = pipeline.predict_proba(X)       # shape: (n_edges, n_classes)
    except Exception as exc:
        log.exception("Inference failed")
        raise HTTPException(status_code=500, detail=f"Inference error: {exc}")

    # ── Build response ────────────────────────────────────────────────────────
    predictions = []
    for i, edge in enumerate(request.edges):
        label = encoder.inverse_transform([encoded_preds[i]])[0]
        prob  = float(probabilities[i].max())           # confidence for predicted class

        log.debug(f"  {edge.id:15s} → {label:<25} (p={prob:.3f})")
        predictions.append(
            EdgePrediction(
                edge_id=edge.id,
                congestion_status=label,
                probability=round(prob, 4),
            )
        )

    log.info(f"Predicted {len(predictions)} edge(s)")
    return PredictResponse(predictions=predictions)
